version: "3.9"

services:
  warp-unlimited:
    image: ghcr.io/thecaduceus/warp-unlimited-docker:okteto
    container_name: warp-unlimited-okteto
    environment:
      - WARP_ID=${WARP_ID}
      - SEND_LOG=${SEND_LOG}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - HIDE_ID=${HIDE_ID}
    ports:
      - 8080:8080
    restart: unless-stopped
